//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Expr.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Three_Musketeers.Grammar {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ExprParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IExprVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExprParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStart([NotNull] ExprParser.StartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExprParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg([NotNull] ExprParser.ProgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExprParser.stm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStm([NotNull] ExprParser.StmContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExprParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] ExprParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExprParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] ExprParser.FunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExprParser.func_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_body([NotNull] ExprParser.Func_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExprParser.printfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintfStatement([NotNull] ExprParser.PrintfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExprParser.scanfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScanfStatement([NotNull] ExprParser.ScanfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExprParser.getsStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGetsStatement([NotNull] ExprParser.GetsStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExprParser.putsStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPutsStatement([NotNull] ExprParser.PutsStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExprParser.att"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtt([NotNull] ExprParser.AttContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SingleAtt</c>
	/// labeled alternative in <see cref="ExprParser.att_var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingleAtt([NotNull] ExprParser.SingleAttContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExprParser.new_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNew_type([NotNull] ExprParser.New_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExprParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgs([NotNull] ExprParser.ArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExprParser.index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndex([NotNull] ExprParser.IndexContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>VarArray</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarArray([NotNull] ExprParser.VarArrayContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CharLiteral</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCharLiteral([NotNull] ExprParser.CharLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AddSub</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddSub([NotNull] ExprParser.AddSubContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Parens</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParens([NotNull] ExprParser.ParensContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Var</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar([NotNull] ExprParser.VarContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UnaryMinus</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryMinus([NotNull] ExprParser.UnaryMinusContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DtoaConversion</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDtoaConversion([NotNull] ExprParser.DtoaConversionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FalseLiteral</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFalseLiteral([NotNull] ExprParser.FalseLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MulDivMod</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMulDivMod([NotNull] ExprParser.MulDivModContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ItoaConversion</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItoaConversion([NotNull] ExprParser.ItoaConversionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>StringLiteral</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringLiteral([NotNull] ExprParser.StringLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TrueLiteral</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrueLiteral([NotNull] ExprParser.TrueLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AtodConversion</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtodConversion([NotNull] ExprParser.AtodConversionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IntLiteral</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntLiteral([NotNull] ExprParser.IntLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DoubleLiteral</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoubleLiteral([NotNull] ExprParser.DoubleLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AtoiConversion</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtoiConversion([NotNull] ExprParser.AtoiConversionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExprParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] ExprParser.TypeContext context);
}
} // namespace Three_Musketeers.Grammar
