//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Expr.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Three_Musketeers.Grammar {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IExprListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class ExprBaseListener : IExprListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart([NotNull] ExprParser.StartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart([NotNull] ExprParser.StartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] ExprParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] ExprParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.stm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStm([NotNull] ExprParser.StmContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.stm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStm([NotNull] ExprParser.StmContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] ExprParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] ExprParser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction([NotNull] ExprParser.FunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction([NotNull] ExprParser.FunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.func_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_body([NotNull] ExprParser.Func_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.func_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_body([NotNull] ExprParser.Func_bodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.printfStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrintfStatement([NotNull] ExprParser.PrintfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.printfStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrintfStatement([NotNull] ExprParser.PrintfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.scanfStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScanfStatement([NotNull] ExprParser.ScanfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.scanfStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScanfStatement([NotNull] ExprParser.ScanfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.getsStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGetsStatement([NotNull] ExprParser.GetsStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.getsStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGetsStatement([NotNull] ExprParser.GetsStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.putsStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPutsStatement([NotNull] ExprParser.PutsStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.putsStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPutsStatement([NotNull] ExprParser.PutsStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.att"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtt([NotNull] ExprParser.AttContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.att"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtt([NotNull] ExprParser.AttContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SingleAtt</c>
	/// labeled alternative in <see cref="ExprParser.att_var"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingleAtt([NotNull] ExprParser.SingleAttContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SingleAtt</c>
	/// labeled alternative in <see cref="ExprParser.att_var"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingleAtt([NotNull] ExprParser.SingleAttContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.new_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNew_type([NotNull] ExprParser.New_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.new_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNew_type([NotNull] ExprParser.New_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgs([NotNull] ExprParser.ArgsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgs([NotNull] ExprParser.ArgsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.index"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndex([NotNull] ExprParser.IndexContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.index"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndex([NotNull] ExprParser.IndexContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>VarArray</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarArray([NotNull] ExprParser.VarArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>VarArray</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarArray([NotNull] ExprParser.VarArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StringLiteral</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringLiteral([NotNull] ExprParser.StringLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StringLiteral</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringLiteral([NotNull] ExprParser.StringLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>CharLiteral</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCharLiteral([NotNull] ExprParser.CharLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>CharLiteral</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCharLiteral([NotNull] ExprParser.CharLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>TrueLiteral</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrueLiteral([NotNull] ExprParser.TrueLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TrueLiteral</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrueLiteral([NotNull] ExprParser.TrueLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MulDiv</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMulDiv([NotNull] ExprParser.MulDivContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MulDiv</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMulDiv([NotNull] ExprParser.MulDivContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AddSub</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddSub([NotNull] ExprParser.AddSubContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AddSub</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddSub([NotNull] ExprParser.AddSubContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Parens</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParens([NotNull] ExprParser.ParensContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Parens</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParens([NotNull] ExprParser.ParensContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Var</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar([NotNull] ExprParser.VarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Var</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar([NotNull] ExprParser.VarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>IntLiteral</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntLiteral([NotNull] ExprParser.IntLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>IntLiteral</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntLiteral([NotNull] ExprParser.IntLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DoubleLiteral</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDoubleLiteral([NotNull] ExprParser.DoubleLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DoubleLiteral</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDoubleLiteral([NotNull] ExprParser.DoubleLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>FalseLiteral</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFalseLiteral([NotNull] ExprParser.FalseLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>FalseLiteral</c>
	/// labeled alternative in <see cref="ExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFalseLiteral([NotNull] ExprParser.FalseLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] ExprParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] ExprParser.TypeContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace Three_Musketeers.Grammar
