string nome = "";
int quantity = 0;
double value = 0.0;
printf("Enter the name of the book: ");
gets(nome);
printf("Enter the quantity of books: ");
scanf(quantity);
printf("Enter the value of the book: ");
scanf(value);
printf("   --- Book Data ---\n");
printf("Name: %s | Quantity: %d | Value: %.2f\n", nome, quantity, value);