string msg = "Welcome to the Three Musketeers";
string name = "";
int quantity = 0;
double value = 0.0;
puts(msg);
puts("Please enter the details of the book");
printf("   --- Enter Book Data ---\n");
printf("Enter the name of the book: ");
gets(name);
printf("Enter the quantity of books: ");
scanf(quantity);
printf("Enter the value of the book: ");
scanf(value);
puts("   --- Book Data ---");
printf("Name: %s | Quantity: %d | Value: %.2f\n", name, quantity, value);